# Generated by Django 2.2 on 2020-08-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
